name: Welcome to Qu
favicon: null
layout_spectrum: 0.27136479690670967
typography_spectrum: 0.8877146786544472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f5ba7'
    - '#ffffff'
    - '#4781bb'
    - '#88add4'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
